server.port=8080

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:empleadosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.initialization-mode=always

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.com.previred=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/openapi.yaml
