spring.application.name=empleados-app
server.port=8080

# JDBC + H2 en memoria
spring.datasource.url=jdbc:h2:mem:empleadosdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.root=INFO
logging.level.com.empleados=DEBUG
logging.level.org.springframework.jdbc=DEBUG

# Jackson
spring.jackson.serialization.indent-output=true

# Swagger UI apunta al spec OpenAPI estatico (contract-first)
springdoc.swagger-ui.url=/openapi/empleados-api.yaml
springdoc.swagger-ui.path=/swagger-ui.html
