package com.mindgrid.empleados.infrastructure.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;

@Configuration
public class DbConnectionConfig {

    private static final Logger LOGGER = Logger.getLogger(DbConnectionConfig.class.getName());

    private static final String DDL =
        "CREATE TABLE IF NOT EXISTS empleados (" +
        "  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "  nombre      VARCHAR(100)  NOT NULL," +
        "  apellido    VARCHAR(100)  NOT NULL," +
        "  rut         VARCHAR(20)   NOT NULL UNIQUE," +
        "  cargo       VARCHAR(100)  NOT NULL," +
        "  salario_base DOUBLE       NOT NULL," +
        "  bono        DOUBLE        NOT NULL DEFAULT 0," +
        "  descuentos  DOUBLE        NOT NULL DEFAULT 0" +
        ")";

    private static final String DATA =
        "INSERT INTO empleados (nombre, apellido, rut, cargo, salario_base, bono, descuentos) " +
        "SELECT 'Juan', 'Pérez', '12345678-5', 'Desarrollador', 500000, 50000, 20000 WHERE NOT EXISTS (SELECT 1 FROM empleados WHERE rut = '12345678-5');" +
        "INSERT INTO empleados (nombre, apellido, rut, cargo, salario_base, bono, descuentos) " +
        "SELECT 'Maria', 'García', '87654321-0', 'Analista', 600000, 60000, 25000 WHERE NOT EXISTS (SELECT 1 FROM empleados WHERE rut = '87654321-0');";

    @Bean
    public DataSource dataSource() {
        DriverManagerDataSource ds = new DriverManagerDataSource();
        ds.setDriverClassName("org.h2.Driver");
        ds.setUrl("jdbc:h2:mem:empleadosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        ds.setUsername("sa");
        ds.setPassword("");

        initSchema(ds);
        return ds;
    }

    private void initSchema(DataSource ds) {
        try (Connection conn = ds.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(DDL);
            stmt.execute(DATA);
            LOGGER.info("Esquema de base de datos inicializado correctamente");
        } catch (SQLException e) {
            throw new RuntimeException("Error al inicializar el esquema de la base de datos", e);
        }
    }
}
