package cl.maraneda.previred.configuration;

import org.springframework.context.annotation.Configuration;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

@Configuration
public class DatabaseConfig {

    @Bean
    CommandLineRunner initDatabase(DataSource dataSource) {
        return args -> {
            String sql = """
                CREATE TABLE IF NOT EXISTS USUARIO (
                    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    NOMBRE VARCHAR(100) NOT NULL,
                    APELLIDO VARCHAR(100) NOT NULL,
                    RUT VARCHAR(10) UNIQUE NOT NULL,
                    CARGO VARCHAR(100) NOT NULL,
                    SALARIO INTEGER NOT NULL,
                    MONTO INTEGER DEFAULT 0
                )
            """;

            try (Connection conn = dataSource.getConnection();
                 Statement stmt = conn.createStatement()) {

                stmt.execute(sql);
            }
        };
    }
}
